name = "race-schedule-scraping"
account_id = "${CLOUDFLARE_ACCOUNT_ID}"
workers_dev = true
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "race-schedule-scraping-html"
preview_bucket_name = "race-schedule-scraping-html-preview"

[env.development]
name = "race-schedule-scraping-dev"

[[env.development.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "race-schedule-scraping-html-dev"

[env.test]
name = "race-schedule-scraping-test"

[[env.test.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "race-schedule-scraping-html-test"

[env.production]
name = "race-schedule-scraping-prod"

[[env.production.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "race-schedule-scraping-html-prod"
